### ISSUE TITLE
generate fr and de - 2264

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/astra-control-center-2204#8]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by ntap-bmegan** [comment]
@netapp-rlithman - Why is localization disabled for this repository?

**Comment by ntap-bmegan** [comment]
@netapp-rlithman - I should rephrase. Why was it disabled for this repository, which has been previously localized.

https://github.com/orgs/NetAppDocs/repositories?q=astra-control-center-2204&type=all

**Comment by ntap-bmegan** [comment]
Configuration is complete. TOT: 10 min
